### ISSUE TITLE
Problem: Request “getblockreward” API failed

### ISSUE THREAD

**Issue by WilliamXieCrypto** [crypto-org-chain/cronos-blockscout#15]
Getting a 500 error response after requesting the “getblockreward”

### Environment

* Elixir 1.11.4-otp-23 & Erlang/OTP 23.3.4.1 
* Operating System: macOS 11.4
* Blockscout Version/branch: master/5f145525ac423acda539fad723ca22fe4c575090

### Steps to reproduce

1. Setup and run on locally
2. Request http://localhost:4000/api?module=block&action=getblockreward&blockno=[replace_this_block_number]
3. You will get the log like below
    `application=block_scout_web request_id=Fpu7W3GsE9iG9rgABK9B [error] Error while calling RPC action"** (Plug.Conn.WrapperError) ** (Ecto.NoResultsError) expected at least one result but got none in query:\n\nfrom b0 in Explorer.Chain.Block,\n  left_join: t1 in assoc(b0, :transactions),\n  join: e2 in Explorer.Chain.Block.EmissionReward,\n  on: fragment(\"? <@ ?\", b0.number, e2.block_range),\n  where: b0.number == ^9200,\n  group_by: [e2.reward],\n  select: %Explorer.Chain.Wei{value: coalesce(sum(t1.gas_used * t1.gas_price), 0) + e2.reward}\n\n    
(ecto 3.5.5) lib/ecto/repo/queryable.ex:159: Ecto.Repo.Queryable.one!/3\n    
(block_scout_web 0.0.1) lib/block_scout_web/controllers/api/rpc/block_controller.ex:12: BlockScoutWeb.API.RPC.BlockController.getblockreward/2\n    
(block_scout_web 0.0.1) lib/block_scout_web/controllers/api/rpc/block_controller.ex:1: BlockScoutWeb.API.RPC.BlockController.action/2\n    
(block_scout_web 0.0.1) lib/block_scout_web/controllers/api/rpc/block_controller.ex:1: BlockScoutWeb.API.RPC.BlockController.phoenix_controller_pipeline/2\n    
(block_scout_web 0.0.1) lib/block_scout_web/controllers/api/rpc/rpc_translator.ex:101: BlockScoutWeb.API.RPC.RPCTranslator.call_controller/3\n    
(block_scout_web 0.0.1) lib/block_scout_web/controllers/api/rpc/rpc_translator.ex:31: BlockScoutWeb.API.RPC.RPCTranslator.call/2\n    
(phoenix 1.5.6) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2\n    
(phoenix 1.5.6) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2\n    
(phoenix 1.5.6) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2\n    
(phoenix 1.5.6) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2\n    
(block_scout_web 0.0.1) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint.plug_builder_call/2\n    
(block_scout_web 0.0.1) lib/plug/debugger.ex:136: BlockScoutWeb.Endpoint.\"call (overridable 3)\"/2\n    
(block_scout_web 0.0.1) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint.\"call (overridable 4)\"/2\n    
(block_scout_web 0.0.1) lib/spandex_phoenix.ex:156: BlockScoutWeb.Endpoint.call/2\n    
(phoenix 1.5.6) lib/phoenix/endpoint/cowboy2_handler.ex:65: Phoenix.Endpoint.Cowboy2Handler.init/4\n    
(cowboy 2.8.0) /Users/<username>/IntelliJProject/cronos-blockscout/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2\n    
(cowboy 2.8.0) /Users/<username>/IntelliJProject/cronos-blockscout/deps/cowboy/src/cowboy_stream_h.erl:300: :cowboy_stream_h.execute/3\n    
(cowboy 2.8.0) /Users/<username>/IntelliJProject/cronos-blockscout/deps/cowboy/src/cowboy_stream_h.erl:291: :cowboy_stream_h.request_process/3\n    
(stdlib 3.14.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3\n"`

### Expected behaviour

This API should response 200 and the response body should be :
`{
  "message": "OK",
  "result": {
    "blockMiner": "0x13a06d3dfe21e0db5c016c03ea7d2509f7f8d1e3",
    "blockNumber": "2165403",
    "blockReward": "5314181600000000000",
    "timeStamp": "1472533979",
    "uncleInclusionReward": null,
    "uncles": null
  },
  "status": "1"
}`

### Actual behaviour

This API response 500 and the response body is:
`{
  "message": "Something went wrong.",
  "result": null,
  "status": "0"
}`

**Comment by WilliamXieCrypto** [comment]
'emission_reward' table is empty. FYI: https://github.com/blockscout/blockscout/issues/4782

**Comment by WilliamXieCrypto** [comment]
Missing Chain specification path: https://docs.blockscout.com/for-developers/information-and-settings/env-variables FYI:https://github.com/blockscout/blockscout/issues/2848

**Comment by WilliamXieCrypto** [comment]
Discussions for this: https://github.com/blockscout/blockscout/discussions/5022
