### ISSUE TITLE
Problem: some internal transactions are not getting indexed and have errors in the logs

### ISSUE THREAD

**Issue by mofhusseini** [crypto-org-chain/cronos-blockscout#67]
Logs from blockscout:

```
** (CaseClauseError) no case clause matching: {:error, [#Ecto.Changeset<action: nil, changes: %{block_number: 580071, call_type: :staticcall, from_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<19, 64, 140, 237, 189, 78, 98, 79, 48, 165, 32, 29, 232, 13, 213, 153, 66, 39, 165, 207>>}, gas: #Decimal<597772>, gas_used: #Decimal<227>, index: 14, input: %Explorer.Chain.Data{bytes: <<50, 191, 228, 105>>}, to_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<129, 73, 32, 209, 184, 0, 114, 7, 219, 108, 181, 162, 221, 146, 191, 11, 8, 43, 219, 161>>}, trace_address: [7, 2], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<38, 42, 34, 89, 233, 164, 90, 133, 249, 155, 217, 25, 107, 3, 147, 191, 207, 157, 212, 187, 93, 248, 20, 255, 81, 140, 145, 65, 185, 143, 97, 109>>}, transaction_index: 14, type: :call, value: #Explorer.Chain.Wei<0>}, errors: [output: {"can't be blank for successful call", [validation: :required]}], data: #Explorer.Chain.InternalTransaction<>, valid?: false>]}
    (indexer 0.1.0) lib/indexer/fetcher/internal_transaction.ex:214: Indexer.Fetcher.InternalTransaction.import_internal_transaction/2
    (indexer 0.1.0) lib/indexer/fetcher/internal_transaction.ex:121: Indexer.Fetcher.InternalTransaction.run/2
    (elixir 1.12.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.12.2) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Indexer.BufferedTask.log_run/1
    Args: [%{batch: [580071, 369393], callback_module: Indexer.Fetcher.InternalTransaction, callback_module_state: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "xxxxxxx", http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], metadata: [fetcher: :internal_transaction]}]
2021-12-24T01:08:13.704 application=indexer fetcher=block_catchup first_block_number=699292 last_block_number=699291 step=receipts [error] failed to fetch: [%{code: -32602, data: %{block_hash: "0x0a4e041266cf1ef31063bda3530b2bdc1c3c7336ac47a4780478b67afbda2d39", block_number: 699292, from_address_hash: "0x00001097f68507836b06b0e1f0222edb0ec91d7b", gas: 460000, gas_price: 5002230571110, hash: "0x9f9389165e4ac0a46241f0bd137f010fdb9e5d84f5ae032e75fe6433e00ac48d", index: 3, input: "0x6ecd2fb700000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000160000000000000000000000000000000000000000000000020117abe60b756000000000000000000000000000000000000000000000000000000000000000001c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000050000000000000000000000005c7f8a570d578ed84e63fdfa7b1ee72deae1ae23000000000000000000000000eb28c926a7afc75fcc8d6671acd4c4a298b3841900000000000000000000000066e428c3f67a68878562e79a0234c1f83c20877000000000000000000000000087d8e223f96a35cd45db5c52e0df646fabb4988c0000000000000000000000005c7f8a570d578ed84e63fdfa7b1ee72deae1ae23000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000026ff00000000000000000000000000000000000000000000000000000000000026fc000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000150dfa7f0000000000000000000000000000000000000000000000201f5d0ad16e760000", nonce: 3284, r: 14165239067437709948196132802259708475397314257811091899522923267394295350124, s: 20054823460700347056743744524864410130021442986829472577771617361799739411332, to_address_hash: "0x8083b5926c2a1d14db4b0decf2674083a3143bb5", transaction_index: 3, type: 0, v: 85, value: 0}, message: "Not Found"}, %{code: -32602, data: %{block_hash: "0x0a4e041266cf1ef31063bda3530b2bdc1c3c7336ac47a4780478b67afbda2d39", block_number: 699292, from_address_hash: "0x000009a87733b2010bbf77ba88b888f242c07ee7", gas: 560000, gas_price: 5002230571110, hash: "0x45021c73d7b2c21893469fa637bf9a932f3408449447386e6badb3c11469eff7", index: 4, input: "0x6ecd2fb700000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000001a000000000000000000000000000000000000000000000000000000000000e46f1000000000000000000000000000000000000000000000000000000000000022000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007000000000000000000000000062e66477faf219f25d27dced647bf57c3107d520000000000000000000000008f09fff247b8fdb80461e5cf5e82dd1ae2ebd6d70000000000000000000000005c7f8a570d578ed84e63fdfa7b1ee72deae1ae23000000000000000000000000a68466208f1a3eb21650320d2520ee8eba5ba623000000000000000000000000c21223249ca28397b4b6541dffaecc539bff0c590000000000000000000000008e3b5a97c1d306499b0588cc57bfe934524671f5000000000000000000000000062e66477faf219f25d27dced647bf57c3107d52000000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000000026f200000000000000000000000000000000000000000000000000000000000026ff00000000000000000000000000000000000000000000000000000000000026f2000000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000002b3ae4ee3fa0280001000000000000000000000000000000000000000000000000000000001c5b368900000000000000000000000000000000000000000000000000000000000e4dc5", nonce: 3265, r: 59437306071538345012392184202085089302080461211490297647846185987910025633154, s: 17266210704528332143690920127838777255044601311347835719081276586344516100722, to_address_hash: "0x8083b5926c2a1d14db4b0decf2674083a3143bb5", transaction_index: 4, type: 0, v: 86, value: 0}, message: "Not Found"}, %{code: -32602, data: %{block_hash: "0x0a4e041266cf1ef31063bda3530b2bdc1c3c7336ac47a4780478b67afbda2d39", block_number: 699292, from_address_hash: "0x69b16f2b0c20f49193eb0c254f6e490b48bb54c0", gas: 200000, gas_price: 5000000000000, hash: "0x12ce921e26fb7ddbcf0efcfb513194fd34a672b25529cbee0b6f4bdb3fe83e55", index: 5, input: "0xe2bbb15800000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000000", nonce: 27, r: 46862562646337781984775261470141495565037540342078598703704194388204979408113, s: 11994490249509040156738795591870860892600801391366237761522184569288693734756, to_address_hash: "0xdccd6455ae04b03d785f12196b492b18129564bc", transaction_index: 5, type: 0, v: 86, value: 0}, message: "Not Found"}, %{code: -32602, data: %{block_hash: "0x0a4e041266cf1ef31063bda3530b2bdc1c3c7336ac47a4780478b67afbda2d39", block_number: 699292, from_address_hash: "0x88972a809c1e06f6b4fb50edc11081b2115cf250", gas: 44407, gas_price: 5000000000000, hash: "0x1915358ca5213fb4e6eec368060b009fe0d095d50ef12bf9dda0d654bb3c6af0", index: 6, input: "0x095ea7b3000000000000000000000000a46c0382654248509a1ed888cccba964693dedcbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", nonce: 200, r: 28470201668230026871133741277057818720455759527005923128048623818517772905347, s: 51849287653619226855347116047998866448183340806226146456151031081590115762179, to_address_hash: "0x2d03bece6747adc00e1a131bba1469c15fd11e03", transaction_index: 6, type: 0, v: 85, value: 0}, message: "Not Found"}, %{code: -32602, data: %{block_hash: "0x0a4e041266cf1ef31063bda3530b2bdc1c3c7336ac47a4780478b67afbda2d39", block_number: 699292, from_address_hash: "0xa86d261d9fceea58b32b95be6686798cc259a7d6", gas: 200000, gas_price: 5000000000000, hash: "0xd580c09f3fde69cd7c774298c03ced4d220426cd9743ecf7b9dac180dc192596", index: 7, input: "0xe2bbb15800000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000", nonce: 88, r: 33553033615494365516807022572572405051149491707793471595046794908750494909117, s: 36889027679697448763295874368129666510525980952240393454368408865647102446105, to_address_hash: "0xdccd6455ae04b03d785f12196b492b18129564bc", transaction_index: 7, type: 0, v: 86, value: 0}, message: "Not Found"}, %{code: -32602, data: %{block_hash: "0x0a4e041266cf1ef31063bda3530b2bdc1c3c7336ac47a4780478b67afbda2d39", block_number: 699292, from_address_hash: "0xb975932fbc9f3cd7c36ba68a298f9e0b8979c83d", gas: 297899, gas_price: 5000000000000, hash: "0xf196ae8cdb01a4d749417280e55b5ce57e8fc7e75a1dc7017a8e1705a5ac5047", index: 8, input: "0xb6f9de9500000000000000000000000000000000000000000001fd1231c5aacd6a00c25d0000000000000000000000000000000000000000000000000000000000000080000000000000000000000000b975932fbc9f3cd7c36ba68a298f9e0b8979c83d0000000000000000000000000000000000000000000000000000000061c521ea00000000000000000000000000000000000000000000000000000000000000030000000000000000000000005c7f8a570d578ed84e63fdfa7b1ee72deae1ae23000000000000000000000000c21223249ca28397b4b6541dffaecc539bff0c59000000000000000000000000dd73dea10abc2bff99c60882ec5b2b81bb1dc5b2", nonce: 58, r: 101523123223991794747209236342820394376054339332138562962963396127598076475384, s: 11489789060672713994846335845492799325073340751911770114130214420365745693840, to_address_hash: "0x145863eb42cf62847a6ca784e6416c1682b1b2ae", transaction_index: 8, type: 0, v: 86, value: 14000000000000000000}, message: "Not Found"}, %{code: -32602, data: %{block_hash: "0x0a4e041266cf1ef31063bda3530b2bdc1c3c7336ac47a4780478b67afbda2d39", block_number: 699292, from_address_hash: "0xbe2eeb8cc038f34c74bdc8c1c3f1e7dae3be8a12", gas: 380000, gas_price: 5000000000000, hash: "0x6c2214bfa7d0483bce2a3c8d4cb711c31a40d0d5a62930dddd36e17b8aa23e69", index: 9, input: "0x2e1a7d4d000000000000000000000000000000000000000000002ed4494f1796c9184d00", nonce: 77, r: 24952349818322107530384963609397119843477259511003481682401284321004118795528, s: 45731115717545648856788848795020879510840299067592661706673941825041125950261, to_address_hash: "0xa6ff77fc8e839679d4f7408e8988b564de1a2dcd", transaction_index: 9, type: 0, v: 85, value: 0}, message: "Not Found"}, %{code: -32602, data: %{block_hash: "0x0a4e041266cf1ef31063bda3530b2bdc1c3c7336ac47a4780478b67afbda2d39", block_number: (truncated)
```

**Comment by ethgr0wth** [comment]
Hi-yah! Any update on this issue, seeing this on our geth powered blockscout

**Comment by bilogate** [comment]
same error to me

**Comment by bilogate** [comment]
Function: &Indexer.BufferedTask.log_run/1
    Args: [%{batch: [5540644, 4237119, 1689205, 4254721, 4254964, 5540656, 4237118, 1698798, 5540630, 1688660], callback_module: Indexer.Fetcher.InternalTransaction, callback_module_state: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://*******:8504", http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], metadata: [fetcher: :internal_transaction]}]
2022-10-05T19:11:35.267 fetcher=internal_transaction count=10 [error] Task #PID<0.4902.17> started from Indexer.Fetcher.InternalTransaction terminating
** (CaseClauseError) no case clause matching: {:error, [#Ecto.Changeset<action: nil, changes: %{block_number: 4207840, call_type: :staticcall, from_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<105, 199, 101, 13, 43, 98, 66, 142, 35, 16, 173, 77, 27, 224, 111, 130, 88, 142, 130, 22>>}, gas: #Decimal<128182>, gas_used: #Decimal<214>, index: 2, input: %Explorer.Chain.Data{bytes: <<187, 59, 175, 214, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1>>}, to_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<81, 168, 163, 178, 188, 159, 229, 139, 188, 201, 119, 124, 158, 35, 87, 230, 19, 242, 215, 45>>}, trace_address: [0, 0], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<85, 102, 145, 240, 194, 63, 46, 119, 230, 21, 90, 14, 37, 201, 115, 98, 252, 38, 209, 218, 126, 197, 4, 35, 87, 48, 189, 241, 155, 232, 235, 108>>}, transaction_index: 0, type: :call, value: #Explorer.Chain.Wei<0>}, errors: [output: {"can't be blank for successful call", [validation: :required]}], data: #Explorer.Chain.InternalTransaction<>, valid?: false>, #Ecto.Changeset<action: nil, changes: %{block_number: 4134260, call_type: :staticcall, from_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<133, 52, 108, 248, 197, 1, 250, 253, 158, 75, 73, 143, 219, 116, 25, 116, 112, 110, 198, 175>>}, gas: #Decimal<141404>, gas_used: #Decimal<236>, index: 2, input: %Explorer.Chain.Data{bytes: <<187, 59, 175, 214, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12>>}, to_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<10, 35, 95, 43, 195, 20, 130, 23, 82, 190, 78, 104, 133, 58, 194, 162, 214, 77, 51, 75>>}, trace_address: [0, 0], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<110, 216, 59, 212, 80, 198, 155, 3, 173, 110, 251, 153, 203, 46, 35, 46, 75, 200, 236, 104, 236, 101, 175, 32, 108, 185, 116, 162, 12, 60, 55, 203>>}, transaction_index: 0, type: :call, value: #Explorer.Chain.Wei<0>}, errors: [output: {"can't be blank for successful call", [validation: :required]}], data: #Explorer.Chain.InternalTransaction<>, valid?: false>, #Ecto.Changeset<action: nil, changes: %{block_number: 4285070, call_type: :staticcall, from_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<30, 206, 181, 96, 183, 47, 26, 208, 214, 124, 9, 70, 226, 152, 152, 43, 29, 89, 65, 96>>}, gas: #Decimal<110814>, gas_used: #Decimal<214>, index: 2, input: %Explorer.Chain.Data{bytes: <<187, 59, 175, 214, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>}, to_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<155, 87, 160, 71, 216, 149, 179, 95, 143, 172, 248, 4, 137, 187, 122, 63, 240, 124, 26, 176>>}, trace_address: [0, 0], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<162, 163, 0, 204, 148, 78, 22, 61, 127, 64, 171, 189, 221, 197, 35, 246, 173, 96, 187, 37, 85, 88, 177, 183, 0, 43, 184, 172, 107, 65, 70, ...>>}, transaction_index: 0, type: :call, value: #Explorer.Chain.Wei<0>}, errors: [output: {"can't be blank for successful call", [validation: :required]}], data: #Explorer.Chain.InternalTransaction<>, valid?: false>, #Ecto.Changeset<action: nil, changes: %{block_number: 4127095, call_type: :staticcall, from_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<133, 52, 108, 248, 197, 1, 250, 253, 158, 75, 73, 143, 219, 116, 25, 116, 112, 110, 198, 175>>}, gas: #Decimal<157562>, gas_used: #Decimal<236>, index: 2, input: %Explorer.Chain.Data{bytes: <<187, 59, 175, 214, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>}, to_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<121, 123, 105, 189, 8, 230, 174, 211, 97, 0, 15, 44, 90, 113, 74, 81, 225, 31, 184, 229>>}, trace_address: [0, 0], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<158, 246, 119, 217, 209, 124, 14, 141, 191, 82, 32, 235, 225, 49, 96, 18, 144, 162, 252, 163, 214, 68, 116, 181, 194, 193, 142, 226, 171, 31, ...>>}, transaction_index: 0, type: :call, value: #Explorer.Chain.Wei<0>}, errors: [output: {"can't be blank for successful call", [validation: :required]}], data: #Explorer.Chain.InternalTransaction<>, valid?: false>, #Ecto.Changeset<action: nil, changes: %{block_number: 4179918, call_type: :staticcall, from_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<105, 199, 101, 13, 43, 98, 66, 142, 35, 16, 173, 77, 27, 224, 111, 130, 88, 142, 130, 22>>}, gas: #Decimal<125082>, gas_used: #Decimal<236>, index: 2, input: %Explorer.Chain.Data{bytes: <<187, 59, 175, 214, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>}, to_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<10, 35, 95, 43, 195, 20, 130, 23, 82, 190, 78, 104, 133, 58, 194, 162, 214, 77, 51, 75>>}, trace_address: [0, 0], transaction_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<82, 26, 146, 99, 126, 122, 95, 247, 28, 65, 171, 51, 22, 214, 54, 104, 30, 255, 231, 70, 1, 216, 57, 152, 183, 35, 0, 30, 124, ...>>}, transaction_index: 0, type: :call, value: #Explorer.Chain.Wei<0>}, errors: [output: {"can't be blank for successful call", [validation: :required]}], data: #Explorer.Chain.InternalTransaction<>, valid?: false>]}
    (indexer 4.1.8) lib/indexer/fetcher/internal_transaction.ex:223: Indexer.Fetcher.InternalTransaction.import_internal_transaction/2
    (indexer 4.1.8) lib/indexer/fetcher/internal_transaction.ex:130: Indexer.Fetcher.InternalTransaction.run/2
    (elixir 1.13.4) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.13.4) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Indexer.BufferedTask.log_run/1
    Args: [%{batch: [4207840, 5540649, 5540648, 4134260, 4285070, 4127095, 1316767, 4179918, 4145190, 5540638], callback_module: Indexer.Fetcher.InternalTransaction, callback_module_state: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://***********:8504", http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], metadata: [fetcher: :internal_transaction]}]

**Comment by girafferz** [comment]
same error
